In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [16]:
dizi =  []
sorgu = requests.get("https://www.sifiraracal.com/otomobil-araba-yorumlari")
sop = BeautifulSoup(sorgu.content,"html.parser")
select=sop.find_all("select",attrs={"class":"yorumyonlendir"})[0].find_all("option")
for options in select:
    if(options["value"]==""):
        continue
    else:
        dizi.append(options["value"])
        
for x in dizi:
    print(x)

alfa-romeo-yorumlari
audi-yorumlari
bmw-yorumlari
citroen-yorumlari
cupra-yorumlari
dacia-yorumlari
dfsk-yorumlari
ds-automobiles-yorumlari
fiat-yorumlari
ford-yorumlari
gazelle-yorumlari
honda-yorumlari
hyundai-yorumlari
isuzu-yorumlari
jaguar-yorumlari
jeep-yorumlari
kia-yorumlari
land-rover-yorumlari
lexus-yorumlari
maserati-yorumlari
mazda-yorumlari
mercedes-yorumlari
mg-yorumlari
mini-yorumlari
mitsubishi-yorumlari
nissan-yorumlari
opel-yorumlari
peugeot-yorumlari
porsche-yorumlari
renault-yorumlari
seat-yorumlari
skoda-yorumlari
skywell-yorumlari
smart-yorumlari
ssangyong-yorumlari
subaru-yorumlari
suzuki-yorumlari
togg-yorumlari
toyota-yorumlari
volkswagen-yorumlari
volvo-yorumlari

In [20]:

import csv 
for i in range(0,len(dizi)):
    istek = requests.get("https://www.sifiraracal.com/"+dizi[i])
    soup = BeautifulSoup(istek.content,"html.parser")
    sayfalar=soup.find_all("div",attrs={"class":"paging"})[0].find_all("a")
    elementsayisi=len(sayfalar)
    toplamsayfa=sayfalar[elementsayisi-1].text
    print(toplamsayfa)

    for sayfano in range(1,int(toplamsayfa)+1):
        istek = requests.get("https://www.sifiraracal.com/"+dizi[i]+"?p="+str(sayfano))
        elementler=BeautifulSoup(istek.content,"html.parser")
        aracmarka=elementler.find_all("div",attrs={"class","b2"})
        for marka in aracmarka:
            aracmarkasi=marka.find("div",attrs={"class":"title"}).a.text
            aracyorumlari=marka.find("div",attrs={"class","yorummesaj"}).text
            file=open("yorumlar.csv","a",newline="")
            yazilacakveri=(dizi[i],aracyorumlari)
            writer=csv.writer(file)
            writer.writerow(yazilacakveri)
            file.close()
        

## print("İstek Doğruluğu : ",istek.status_code)

8
59
32
58
1
50
1
5
87
81
1
74
72
3
12
13
45
9
6
2
17
26
1
9
17
43
53
45
3
78
23
45
1
1
15
10
19
1
46
51
25

In [1]:
import pandas as pd
import re
from pandas import option_context
df=pd.read_csv('yorumlar.csv')
print("Orjinal Veri Seti Veri Sayısı : "+str(len(df)))
print("Orjinal Veri Setindeki Tekrar Eden Veri Sayısı : "+str(df.duplicated().sum()))
print("Veri Setinde Tekil Olan Veri Sayısı "+str(df["Araç Yorumları"].nunique()))
print(df.dtypes)
with option_context('display.max_colwidth',400):
    display(df.head(300))

Orjinal Veri Seti Veri Sayısı : 33836
Orjinal Veri Setindeki Tekrar Eden Veri Sayısı : 11626
Veri Setinde Tekil Olan Veri Sayısı 22005
Araç Markası      object
Araç Yorumları    object
dtype: object

,Araç Markası,Araç Yorumları
0,alfa-romeo-yorumlari,"\nŞu sıra bir 2012 modele bütçem yetiyor, alınır mı, kronik sorunları varb mıdır?\n"
1,alfa-romeo-yorumlari,"\nKimisinin beklentilerini karşılayamamış olabilir. Alman araçlarını kullanmış birisi olarak şunu söyleyeyim bu araba motor gücü, estetik dizaynı ve iç konforu ile sahibine yırtıcı bir\n"
2,alfa-romeo-yorumlari,\nGuzel araç üst sınıf biraz porche tipli ama massarati de destek vermiş türkiye de gider\n
3,alfa-romeo-yorumlari,\nkeşke bu güzel araç için başka paketlerde olsaydı\n
4,alfa-romeo-yorumlari,\nsedan araçlarda beğendiğim bir tür ve iç hacmi çok geniş\n
...,...,...
295,audi-yorumlari,\nArkadaşlar 2019 a3 sedan kullanıyorum yağmurda siecekler çalıştığında sol kapı camından dere akıyor sanki aynayı göremiyorum sileceğin sildiği bütün su kapı camından gidiyor sizdede böyle bir sorun varmı yoksa benim arabamı hatalı.. Geri kalan herşeyinden çok memnunum\n
296,audi-yorumlari,\nvaliysen yapıştır\n
297,audi-yorumlari,\nvaliysen yapıştır\n
298,audi-yorumlari,\nValiysen hiç düşünme çak bi tane\n
299,audi-yorumlari,\nValiysen hiç düşünme çak bi tane\n

In [2]:
import re
import pandas as pd
from pandas import option_context
df=pd.read_csv('yorumlar.csv')
df = df.drop_duplicates(subset="Araç Yorumları", keep="first", inplace=False)
df.to_csv("dataset.csv", index=False)
df=pd.read_csv("dataset.csv")

df['Araç Markası'] = df['Araç Markası'].str.split('-yorumlari').str[0] ## Araç Markası Sütunundaki -yorumlari kaldırır
df['Araç Yorumları'] = df['Araç Yorumları'].str.lower() ## Araç Yorumları Sütunundaki harfleri küçük yapar.
for index,cumle in enumerate(df["Araç Yorumları"]):
    df["Araç Yorumları"][index]=re.sub('[?|$|.|!|,|...|:|)|\n]'," ",str(cumle))

    
df = df.replace("alfa-romeo","alfa romeo")
df = df.replace("land-rover","land rover") 
with option_context('display.max_colwidth',400):
    display(df.head(300))

,Araç Markası,Araç Yorumları
0,alfa romeo,şu sıra bir 2012 modele bütçem yetiyor alınır mı kronik sorunları varb mıdır
1,alfa romeo,kimisinin beklentilerini karşılayamamış olabilir alman araçlarını kullanmış birisi olarak şunu söyleyeyim bu araba motor gücü estetik dizaynı ve iç konforu ile sahibine yırtıcı bir
2,alfa romeo,guzel araç üst sınıf biraz porche tipli ama massarati de destek vermiş türkiye de gider
3,alfa romeo,keşke bu güzel araç için başka paketlerde olsaydı
4,alfa romeo,sedan araçlarda beğendiğim bir tür ve iç hacmi çok geniş
...,...,...
295,audi,2010 a4 b8 kasa 2 0tfsi almayı düşünüyorum temiz araç yağ yakma problemi yok uzun kullanımda problem çıkarırmı
296,audi,merhaba arkadaşlar 2017 a3 sedan 1 6 tdi spot line almayı düşünüyorum paket olarak nasıl diğer paketler arasında çok fark var mı hangi paket daha az yakıyor tavsiye edermısınız
297,audi,mrb kolay gelsin 2018 model a4 1 4tfs motor dynamic düşünüyorum aracı kullanan veya bilenler aracı kronik sorunu varmı bilgi verirmisiniz şimdi den çok teşekkür ederim
298,audi,benim olmalıydın
299,audi,araç çok güzel hiç tereddüt etmeden gönül rahatlığıyla alabilirsiniz uçak almayın bunu alın

In [6]:
#############################################FİNAL#######################################################
#ingilizceye çevirme
import googletrans 
from googletrans import Translator
translator = Translator()
ingilizce_yorumlar = []
index=0;
for cumle in df["Araç Yorumları"]:
    clear_output(wait=True)
    index=index+1
    print(index)
    ingilizce_yorumlar.append(translator.translate(cumle).text)
    

print("İşlem Tamamlandı.");

22005
İşlem Tamamlandı.

In [3]:
ingilizce_set=pd.read_csv("ingilizce.csv")
for index,cumle in enumerate(ingilizce_set["ingilizce_yorumlar"]):
    ingilizce_set["ingilizce_yorumlar"][index]=re.sub('',"",str(cumle))
ingilizce_set

      Araç Markası                                 ingilizce_yorumlar
0       alfa romeo  at the moment i can afford a 2012 model, can i...
1       alfa romeo  It may not have met the expectations of some, ...
2       alfa romeo  nice car, top class, a bit porsche type, but m...
3       alfa romeo  I wish there were other packages for this beau...
4       alfa romeo  It is a type that I like in sedan vehicles and...
...            ...                                                ...
22000        volvo  A vehicle that deserves to receive 5 stars in ...
22001        volvo  I have requested a test drive. I will enjoy th...
22002        volvo                            very nice for the money
22003        volvo  I was prejudiced before I bought it, after I b...
22004        volvo  Apart from its price and features, it stands o...

[22005 rows x 2 columns]

In [4]:
##Stopwordsleri bulma işlemi
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bahad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
swords=set(stopwords.words("english"))
swords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [6]:
ornek_metin = ingilizce_set["ingilizce_yorumlar"][0]
ornek_metin=ornek_metin.split()
print(ornek_metin," Kelime Sayısı : ",len(ornek_metin))

['at', 'the', 'moment', 'i', 'can', 'afford', 'a', '2012', 'model,', 'can', 'i', 'buy', 'it', 'or', 'do', 'they', 'have', 'any', 'chronic', 'problems?']  Kelime Sayısı :  20

In [7]:
swords=set(stopwords.words("english"))
ornek_metin=[w for w in ornek_metin if w not in swords]
print(ornek_metin," Kelime Sayısı : ",len(ornek_metin))

['moment', 'afford', '2012', 'model,', 'buy', 'chronic', 'problems?']  Kelime Sayısı :  7

In [8]:
def temizlemeislemi(review):
    review=review.split()
    swords=set(stopwords.words("english"))
    review=[w for w in review if w not in swords]
    return (" ".join(review))

In [9]:
from IPython.display import clear_output
train_x=[]
for i in range(len(ingilizce_set["ingilizce_yorumlar"])):
    if(i+1)%1000==0:
        clear_output(wait=True)
        print("İşlem Adımı",i+1)
    train_x.append(temizlemeislemi(ingilizce_set["ingilizce_yorumlar"][i]))

İşlem Adımı 22000

In [10]:
ingilizce_set.drop(['ingilizce_yorumlar'], axis=1, inplace=True)

In [11]:
ingilizce_set["no_stopwords_comment"]=train_x

In [12]:
ingilizce_set

      Araç Markası                               no_stopwords_comment
0       alfa romeo    moment afford 2012 model, buy chronic problems?
1       alfa romeo  It may met expectations some, someone used Ger...
2       alfa romeo  nice car, top class, bit porsche type, maserat...
3       alfa romeo                  I wish packages beautiful vehicle
4       alfa romeo  It type I like sedan vehicles interior volume ...
...            ...                                                ...
22000        volvo  A vehicle deserves receive 5 stars euro ncap t...
22001        volvo  I requested test drive. I enjoy ride next week...
22002        volvo                                         nice money
22003        volvo  I prejudiced I bought it, I bought it, questio...
22004        volvo  Apart price features, stands vehicles class ac...

[22005 rows x 2 columns]

In [13]:
##TEXT BLOB KULLANARAK ------- RandomForestClassifier
from textblob import TextBlob
ingilizce_set["text_blob_sonuc"]=ingilizce_set["no_stopwords_comment"].map(lambda x:TextBlob(x).sentiment.polarity)
ingilizce_set

,Araç Markası,no_stopwords_comment,text_blob_sonuc
0,alfa romeo,"moment afford 2012 model, buy chronic problems?",0.000000
1,alfa romeo,"It may met expectations some, someone used Ger...",0.000000
2,alfa romeo,"nice car, top class, bit porsche type, maserat...",0.550000
3,alfa romeo,I wish packages beautiful vehicle,0.850000
4,alfa romeo,It type I like sedan vehicles interior volume ...,0.214286
...,...,...,...
22000,volvo,A vehicle deserves receive 5 stars euro ncap t...,0.000000
22001,volvo,I requested test drive. I enjoy ride next week...,0.200000
22002,volvo,nice money,0.600000
22003,volvo,"I prejudiced I bought it, I bought it, questio...",0.000000
22004,volvo,"Apart price features, stands vehicles class ac...",0.000000

In [14]:
for i in ingilizce_set["text_blob_sonuc"]:
    if(i<0):
        ingilizce_set["text_blob_sonuc"].replace(to_replace=i,value="0",inplace=True)
    elif(i>=0):
        ingilizce_set["text_blob_sonuc"].replace(to_replace=i,value="1",inplace=True)

In [15]:
ingilizce_set["text_blob_sonuc"].value_counts()
ingilizce_set.tail(18)

,Araç Markası,no_stopwords_comment,text_blob_sonuc
21987,volvo,"When I bought car, everyone around said car ca...",1
21988,volvo,"volvo's vehicles similar other, friend",0
21989,volvo,"solid also strong vehicle, I say solid cars.",1
21990,volvo,"dream car, it'll favor I save buy car, they're...",1
21991,volvo,"family car dreams, fill children, take long tr...",1
21992,volvo,brand expensive solid image,0
21993,volvo,"volvo makes solid vehicle, friend",1
21994,volvo,solid vehicle mashallah,1
21995,volvo,one cars reflect solidity image,1
21996,volvo,"If want speed, safety, economical fuel high pe...",1
21997,volvo,"If going buy diesel model, I say economical you.",1
21998,volvo,"comes durability, name immediately comes mind ...",1
21999,volvo,"The suspension system successful, feel vibrati...",1
22000,volvo,A vehicle deserves receive 5 stars euro ncap t...,1
22001,volvo,I requested test drive. I enjoy ride next week...,1
22002,volvo,nice money,1
22003,volvo,"I prejudiced I bought it, I bought it, questio...",1
22004,volvo,"Apart price features, stands vehicles class ac...",1

In [29]:
##degisken=pd.crosstab(ingilizce_set["Araç Markası"],ingilizce_set["text_blob_sonuc"]).apply(lambda r:r/r.sum(),axis=1)
##degisken.sort_values(by='0', ascending=False)

In [16]:
from sklearn.model_selection import train_test_split
x=train_x
y=np.array(ingilizce_set["text_blob_sonuc"])
train_1,test_1,train_2,test_2=train_test_split(x,y,test_size=0.15,random_state=42)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer =CountVectorizer(max_features=5000)
train_x1=vectorizer.fit_transform(train_1)
train_x1

<18704x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 192596 stored elements in Compressed Sparse Row format>

In [18]:
train_x1=train_x1.toarray()

In [19]:
train_x1.shape,train_2.shape

((18704, 5000), (18704,))

In [20]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(train_x1,train_2)

RandomForestClassifier()

In [21]:
test_x1=vectorizer.transform(test_1)

In [22]:
test_x1

<3301x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 33764 stored elements in Compressed Sparse Row format>

In [23]:
from sklearn.metrics import roc_auc_score
test_predict=rf.predict(test_x1)
dogruluk=roc_auc_score(test_2,test_predict)
dogruluk

0.8292675547611733

In [24]:
from sklearn.metrics import classification_report
print(classification_report(test_2,test_predict))

              precision    recall  f1-score   support

           0       0.76      0.69      0.72       366
           1       0.96      0.97      0.97      2935

    accuracy                           0.94      3301
   macro avg       0.86      0.83      0.84      3301
weighted avg       0.94      0.94      0.94      3301

In [25]:
markalar=[]
for cumle in test_1:
    index=np.where(cumle==ingilizce_set["no_stopwords_comment"])
    if(len(index[0])!=0):
        yer=index[0][0]
        markalar.append(ingilizce_set["Araç Markası"][yer])
    
print(len(markalar))

3301

In [26]:
forest_veriseti=pd.read_csv('forest.csv')
forest_veriseti["Araç Markası"]=markalar
forest_veriseti["Araç Yorumları"]=test_1
forest_veriseti["Tahmin Edilen Sonuçlar"]=test_predict
forest_veriseti

,Araç Markası,Araç Yorumları,Tahmin Edilen Sonuçlar
0,hyundai,"The fuel consumption normal city, average arou...",0
1,ford,"I riding transit years, latest 2020 model fron...",1
2,volvo,volvo always dream using v60 2012 model number...,1
3,skoda,"I 10 mpi engine fabia, traction performance ex...",1
4,audi,The thing I like vehicle trunk volume wide sea...,1
...,...,...,...
3296,ford,"These rims suit car, suit car.",1
3297,mercedes,"car performance, speed aesthetics meet",1
3298,bmw,car different charisma,1
3299,ford,unique tool segment simply awesome,1
3300,nissan,"2 years ago, I bought brand new 2018 April 201...",1

In [27]:
degisken=pd.crosstab(forest_veriseti["Araç Markası"],forest_veriseti["Tahmin Edilen Sonuçlar"]).apply(lambda r:r/r.sum(),axis=1)
degisken.sort_values(by='1', ascending=False)

Tahmin Edilen Sonuçlar         0         1
Araç Markası
cupra                   0.000000  1.000000
mg                      0.000000  1.000000
dfsk                    0.000000  1.000000
togg                    0.000000  1.000000
porsche                 0.000000  1.000000
skywell                 0.000000  1.000000
skoda                   0.026549  0.973451
mini                    0.038462  0.961538
audi                    0.047619  0.952381
lexus                   0.052632  0.947368
suzuki                  0.062500  0.937500
volkswagen              0.063830  0.936170
kia                     0.069307  0.930693
hyundai                 0.077844  0.922156
mercedes                0.077922  0.922078
mitsubishi              0.080000  0.920000
honda                   0.080460  0.919540
fiat                    0.080882  0.919118
ds-automobiles          0.083333  0.916667
seat                    0.095238  0.904762
volvo                   0.097826  0.902174
ssangyong               0.098361  0.901639
citroen                 0.100000  0.900000
dacia                   0.109827  0.890173
peugeot                 0.110345  0.889655
alfa romeo              0.115385  0.884615
toyota                  0.119718  0.880282
maserati                0.125000  0.875000
nissan                  0.127451  0.872549
mazda                   0.129032  0.870968
subaru                  0.130435  0.869565
ford                    0.132812  0.867188
jeep                    0.133333  0.866667
renault                 0.134783  0.865217
opel                    0.136986  0.863014
bmw                     0.146067  0.853933
isuzu                   0.200000  0.800000
land rover              0.250000  0.750000
jaguar                  0.250000  0.750000
gazelle                 0.500000  0.500000
smart                   1.000000  0.000000

In [28]:
## VADER MODÜLÜ KULLANARAK  -------- KNeighborsClassifier
ingilizce_set.drop(['text_blob_sonuc'], axis=1, inplace=True)
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
def hesapla(text):
    over_all_polarity=model.polarity_scores(text)
    if over_all_polarity['compound'] >=0.05:
        return "1"
    else:
        return "0"


model = SentimentIntensityAnalyzer()
ingilizce_set["vader_sonuc"]=ingilizce_set['no_stopwords_comment'].apply(lambda x:hesapla(x))
ingilizce_set

,Araç Markası,no_stopwords_comment,vader_sonuc
0,alfa romeo,"moment afford 2012 model, buy chronic problems?",0
1,alfa romeo,"It may met expectations some, someone used Ger...",1
2,alfa romeo,"nice car, top class, bit porsche type, maserat...",1
3,alfa romeo,I wish packages beautiful vehicle,1
4,alfa romeo,It type I like sedan vehicles interior volume ...,1
...,...,...,...
22000,volvo,A vehicle deserves receive 5 stars euro ncap t...,0
22001,volvo,I requested test drive. I enjoy ride next week...,1
22002,volvo,nice money,1
22003,volvo,"I prejudiced I bought it, I bought it, questio...",0
22004,volvo,"Apart price features, stands vehicles class ac...",0

In [30]:
ingilizce_set["vader_sonuc"].value_counts()

1    14700
0     7305
Name: vader_sonuc, dtype: int64

In [110]:
##degisken=pd.crosstab(ingilizce_set["Araç Markası"],ingilizce_set["vader_sonuc"]).apply(lambda r:r/r.sum(),axis=1)
##degisken.sort_values(by='1', ascending=False)

In [31]:
from sklearn.model_selection import train_test_split
x=train_x
y=np.array(ingilizce_set["vader_sonuc"])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=35)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer =CountVectorizer(max_features=5000)
x_train_knn=vectorizer.fit_transform(x_train)
x_train_knn.shape,y_train.shape

((18704, 5000), (18704,))

In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train_knn,y_train)

KNeighborsClassifier()

In [34]:
from sklearn.metrics import roc_auc_score
knn_test=vectorizer.transform(x_test)
sonuc=knn.predict(knn_test)
dogruluk=roc_auc_score(y_test,sonuc)
dogruluk

0.7901513677606946

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,sonuc))

              precision    recall  f1-score   support

           0       0.59      0.90      0.71      1114
           1       0.93      0.68      0.79      2187

    accuracy                           0.75      3301
   macro avg       0.76      0.79      0.75      3301
weighted avg       0.82      0.75      0.76      3301

In [36]:
markalar=[]
for cumle in x_test:
    index=np.where(cumle==ingilizce_set["no_stopwords_comment"])
    if(len(index[0])!=0):
        yer=index[0][0]
        markalar.append(ingilizce_set["Araç Markası"][yer])
    
print(len(markalar))

3301

In [37]:
knn_veriseti=pd.read_csv('forest.csv')
knn_veriseti["Araç Markası"]=markalar
knn_veriseti["Araç Yorumları"]=x_test
knn_veriseti["Tahmin Edilen Sonuçlar"]=sonuc
knn_veriseti

,Araç Markası,Araç Yorumları,Tahmin Edilen Sonuçlar
0,skoda,"The starting price affordable, technical featu...",1
1,suzuki,that's,0
2,fiat,I'm one terms comfort price,0
3,citroen,"I'm buying new 2010 model, hardware nice, I'm ...",0
4,dacia,"I experienced many vehicles far, stepway defin...",1
...,...,...,...
3296,dacia,"I bought it, regret bro, gear low, like Taurus...",1
3297,nissan,I'm thinking buying 2020 model sky pack 1 5 di...,1
3298,hyundai,"I using 1 year, I satisfied, fuel comfort type...",1
3299,peugeot,"hello, someone uses 1 2 gasoline manual commen...",0
3300,opel,"I've using 1 year, make sad",1

In [38]:
degisken=pd.crosstab(knn_veriseti["Araç Markası"],knn_veriseti["Tahmin Edilen Sonuçlar"]).apply(lambda r:r/r.sum(),axis=1)
degisken.sort_values(by='1', ascending=False)

Tahmin Edilen Sonuçlar         0         1
Araç Markası
mini                    0.250000  0.750000
ds-automobiles          0.307692  0.692308
ssangyong               0.358491  0.641509
skywell                 0.400000  0.600000
seat                    0.413793  0.586207
land rover              0.440000  0.560000
alfa romeo              0.441860  0.558140
porsche                 0.444444  0.555556
jaguar                  0.454545  0.545455
jeep                    0.454545  0.545455
audi                    0.455696  0.544304
volvo                   0.458333  0.541667
suzuki                  0.461538  0.538462
toyota                  0.475000  0.525000
opel                    0.480916  0.519084
bmw                     0.484536  0.515464
skoda                   0.495798  0.504202
fiat                    0.498270  0.501730
cupra                   0.500000  0.500000
mercedes                0.506667  0.493333
citroen                 0.514620  0.485380
volkswagen              0.525547  0.474453
lexus                   0.526316  0.473684
nissan                  0.527273  0.472727
mazda                   0.527778  0.472222
mitsubishi              0.532258  0.467742
renault                 0.535581  0.464419
ford                    0.541322  0.458678
dacia                   0.550725  0.449275
peugeot                 0.557576  0.442424
hyundai                 0.570000  0.430000
kia                     0.574074  0.425926
subaru                  0.576923  0.423077
honda                   0.617284  0.382716
maserati                0.666667  0.333333
isuzu                   0.666667  0.333333
mg                      0.750000  0.250000
smart                   1.000000  0.000000

In [46]:
###### Naive-Bayes Algoritması #####
from sklearn.feature_extraction.text import CountVectorizer
vectorizer =CountVectorizer(max_features=5000)
x_train_bayes=vectorizer.fit_transform(x_train)
x_train_bayes.shape,y_train.shape

((18704, 5000), (18704,))

In [47]:
from sklearn.naive_bayes import BernoulliNB
x_train_bayes=x_train_bayes.toarray()
nb = BernoulliNB()
modelim=nb.fit(x_train_bayes,y_train)

In [48]:
test_bayes=vectorizer.transform(x_test)
test_bayes

<3301x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 33154 stored elements in Compressed Sparse Row format>

In [49]:
test_bayes = test_bayes.toarray()
test_bayes

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [50]:
from sklearn.metrics import roc_auc_score
predit=nb.predict(test_bayes)
predit_object = np.array(predit, dtype=object)
roc_auc_score(y_test,predit_object)

0.8417542373368337

In [51]:
print(classification_report(y_test,predit_object))

              precision    recall  f1-score   support

           0       0.80      0.78      0.79      1114
           1       0.89      0.90      0.90      2187

    accuracy                           0.86      3301
   macro avg       0.84      0.84      0.84      3301
weighted avg       0.86      0.86      0.86      3301